config/routes.rb
EZBrm::Application.routes.draw do

  devise_for :users

  resources :users do
    resources :locations do
      resources :competitors
    end
  end

  root :to => "users#show"

end

app/models/competitor.rb
# This represents a competitor to a location
class Competitor < ActiveRecord::Base
  belongs_to :location

  validates :name, presence: true
  validates :url, presence: true
  validates :image_url, presence: true
  validates :category, presence: true
  validates :review_count, presence: true
end

app/models/location.rb
# This represents your startup
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :category, :name
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  belongs_to :user
  has_many :competitors

  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :category, presence: true
  validates :name, presence: true

  # Add some validations here
  def get_info
    client = Yelp::Client.new
    category = self.category
    latitude = self.latitude
    longitude = self.longitude

    request = Yelp::V2::Search::Request::GeoPoint.new(
             :term => category,
             :latitude => latitude,
             :longitude => longitude)
    response = client.search(request)
    @stores = response["businesses"]

    @stores.each do |store|

      @competitor = Competitor.new
      @competitor.name = store["name"]
      @competitor.review_count = store["review_count"]
      @competitor.url = store["url"]
      @competitor.image_url = store["image_url"]
      @competitor.category = store["categories"][0][0]
      @competitor.save!
      self.competitors << @competitor
    end
  end
end

app/models/user.rb
# This represents the users who can login
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :remember_me,
                  :username

  has_many :locations

end

app/controllers/application_controller.rb
# this is the main controller that all others inherit from
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
# This is the main controller for our Locations of the startups
class LocationsController < ApplicationController
  before_action :get_user
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create!(params[:location])
    @location.get_info
    current_user.locations << @location
    if @location.save
      redirect_to current_user, :notice => "Successfully created location."
    else
      render :action => 'new'
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    @location.get_info
    if @location.update_attributes(params[:location])
      redirect_to current_user, :notice  => "Successfully updated location."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to user_path, :notice => "Successfully destroyed location."
  end

  private

  def get_user
    @user = User.find(params[:user_id]) if params.key?(:user_id)
  end

end

app/controllers/users_controller.rb
# This is our user controller for setting the current user and login
class UsersController < ApplicationController
   before_filter :authenticate_user!
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EZBrm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="jumbotron">

  	<div id="container">
  		<h1>EZ-brm</h1>
  		<h2>Check your Potential Competitors.</h2>
  		<div class="text-left margin-left">
  			<% if user_signed_in? %>
  			  Logged in as <strong><%= current_user.email %></strong>.
  			  <%= link_to 'Edit profile', edit_user_registration_path %> |
  			  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  			<% else %>
  			  <%= link_to "Sign up", new_user_registration_path %> |
  			  <%= link_to "Login", new_user_session_path %>
  			<% end %>
  		</div>
  	</div>
</div>



<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for [@user, @location] do |f| %>
<div class="container" style="margin-left:163px">
  <p>
    <%= f.label :name %></br>
    <%= f.text_field :name %></br>
    <%= f.label :category %></br>
    <%= f.text_field :category %></br>
    <%= f.label :address %></br>
    <%= f.text_field :address %>
  </p>
  <p><%= f.submit %></p>
</div>
<% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>

<div class="container" style="margin-left:163px">
  <p>
    <%= link_to "Show", [@user, @location] %> |
    <%= link_to "View All", user_locations_path %>
  </p>
</div>

app/views/locations/index.html.erb
<button type="button" class="btn btn-default btn-lg"><%= link_to "Create a new startup!", new_user_location_path(current_user.id) %>
</button>

<table class="user-table">

  <tr>
    <th>Name</th>
    <th class="long">Address</th>
    <th>category</th>
  </tr>
  <% for location in current_user.locations %>
    <tr>
      <td><%= location.name %></td>
      <td><%= location.address %></td>
      <td><%= location.category %></td>

      <td>
        <button type="button" class="btn btn-default btn-md">
          </span> <%= link_to "Show", user_location_path(current_user.id, location) %>
        </button>

        <button type="button" class="btn btn-default btn-md">
          </span> <%= link_to "Edit", edit_user_location_path(current_user.id, location) %>
        </button>

        <button type="button" class="btn btn-default btn-md">
          </span> <%= link_to "Destroy", user_location_path(current_user, location), :confirm => 'Are you sure?', :method => :delete %>
        </button>
      </td>
    </tr>
  <% end %>
</table>

app/views/locations/new.html.erb
<%= render 'form' %>

app/views/locations/show.html.erb
<style>

</style>
<div class="container">
<button type="button" class="btn btn-default btn-lg"><%= link_to "Back to Startup List", user_locations_path %>
</button>

  <div class="row text-white">
        <% @location.competitors.each do |competitor| %>
          <% if competitor.review_count >= 50 %>
            <div class="col-xs-6 col-sm-6 col-md-6 margin-top" >
              <div class="col-xs-3 col-sm-3 col-md-3" >
                <img src='<%= competitor.image_url %>'>
              </div>
              <div class="col-xs-4 col-sm-4 col-md-4" >
                <button type="button" class="btn btn-default btn-md">
                <span class="glyphicon glyphicon-leaf"></span> <%= link_to competitor.name, competitor.url %>
                </button>
              </div>
              <div class="col-xs-5 col-sm-5 col-md-5" >
                <p style="font-size:15px;">Category: <%= competitor.category %></p>
                <p style="font-size:15px;">Review count: <%= competitor.review_count %></p></br>
              </div>
            </div>
          <% end %>
        <% end %>
  </div>
</div>

app/views/users/show.html.erb
<link href="style.css" rel="stylesheet">

<button type="button" class="btn btn-default btn-lg"><%= link_to "Create a new startup!", new_user_location_path(current_user.id) %>
</button>



<table class="user-table">

  <tr>
    <th>Name</th>
    <th class="long">Address</th>
    <th>category</th>
  </tr>
  <% for location in current_user.locations %>
    <tr>
      <td><%= location.name %></td>
      <td><%= location.address %></td>
      <td><%= location.category %></td>

      <td>
        <button type="button" class="btn btn-default btn-md">
          </span> <%= link_to "Show", user_location_path(current_user.id, location) %>
        </button>

        <button type="button" class="btn btn-default btn-md">
          </span> <%= link_to "Edit", edit_user_location_path(current_user.id, location) %>
        </button>

        <button type="button" class="btn btn-default btn-md">
          </span> <%= link_to "Destroy", user_location_path(current_user, location), :confirm => 'Are you sure?', :method => :delete %>
        </button>
      </td>
    </tr>
  <% end %>
</table>